# Generated by Django 4.2.27 on 2026-01-24 12:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoteValidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_lote', models.CharField(db_index=True, max_length=50, verbose_name='Número do Lote')),
                ('data_validade', models.DateField(db_index=True, verbose_name='Data de Validade')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('qtd_estoque', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em Estoque')),
                ('localizacao', models.CharField(blank=True, help_text='Posição física no estoque (ex: A1-P2-N3)', max_length=50, null=True, verbose_name='Localização')),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Unitário')),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Lote/Validade',
                'verbose_name_plural': 'Lotes/Validades',
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_unb', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código UNB')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Unidade')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Unidade de Negócio',
                'verbose_name_plural': 'Unidades de Negócio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('OPERADOR', 'Operador'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente')], default='OPERADOR', max_length=50, verbose_name='Papel na Unidade')),
                ('data_vinculo', models.DateField(auto_now_add=True, verbose_name='Data de Vínculo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadenegocio', verbose_name='Unidade de Negócio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Unidade',
                'verbose_name_plural': 'Vínculos Usuário-Unidade',
                'unique_together': {('usuario', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_sku', models.CharField(db_index=True, max_length=50, verbose_name='Código SKU')),
                ('nome_produto', models.CharField(db_index=True, max_length=255, verbose_name='Nome do Produto')),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Categoria')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('L', 'Litro'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('FD', 'Fardo'), ('M', 'Metro')], default='UN', max_length=5, verbose_name='Unidade de Medida')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, help_text='Foto do produto para exibição no app', null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='core.unidadenegocio', verbose_name='Unidade de Negócio')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste')], max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('EM_TRANSITO', 'Em Trânsito'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='EM_TRANSITO', max_length=15, verbose_name='Status')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista')),
                ('data_efetiva', models.DateField(blank=True, null=True, verbose_name='Data Efetiva')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('lote', models.ForeignKey(blank=True, help_text='Lote específico (obrigatório para saída)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.lotevalidade', verbose_name='Lote')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.sku', verbose_name='SKU')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_entrada', to='core.unidadenegocio', verbose_name='Unidade Destino')),
                ('unidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_saida', to='core.unidadenegocio', verbose_name='Unidade Origem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lotevalidade',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.sku', verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='LogConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_consulta', models.CharField(choices=[('VALIDADE', 'Consulta de Validade'), ('CRITICIDADE', 'Relatório de Criticidade'), ('ESTOQUE', 'Consulta de Estoque')], max_length=50, verbose_name='Tipo de Consulta')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Consulta',
                'verbose_name_plural': 'Logs de Consulta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dias_para_critico', models.PositiveIntegerField(default=30, help_text='Quantidade de dias antes do vencimento para status CRÍTICO', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Crítico')),
                ('dias_para_pre_bloqueio', models.PositiveIntegerField(default=45, help_text='Quantidade de dias antes do vencimento para status PRÉ-BLOQUEIO', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Pré-Bloqueio')),
                ('unidade', models.OneToOneField(blank=True, help_text='Se vazio, será configuração global padrão', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_alerta', to='core.unidadenegocio', verbose_name='Unidade de Negócio')),
            ],
            options={
                'verbose_name': 'Configuração de Alerta',
                'verbose_name_plural': 'Configurações de Alerta',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidades',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='core.UsuarioUnidade', to='core.unidadenegocio', verbose_name='Unidades de Acesso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['codigo_sku', 'unidade_negocio'], name='core_sku_codigo__01d92a_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['nome_produto'], name='core_sku_nome_pr_4bd6c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('codigo_sku', 'unidade_negocio')},
        ),
        migrations.AddIndex(
            model_name='lotevalidade',
            index=models.Index(fields=['data_validade'], name='core_loteva_data_va_49c65c_idx'),
        ),
        migrations.AddIndex(
            model_name='lotevalidade',
            index=models.Index(fields=['sku', 'data_validade'], name='core_loteva_sku_id_321d60_idx'),
        ),
        migrations.AddIndex(
            model_name='lotevalidade',
            index=models.Index(fields=['numero_lote'], name='core_loteva_numero__51e160_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lotevalidade',
            unique_together={('sku', 'numero_lote')},
        ),
    ]
