# Generated by Django 4.2.27 on 2026-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('FD', 'Fardo')], default='UN', max_length=5, verbose_name='Unidade de Medida'),
        ),
    ]
