# Generated by Django 4.2.27 on 2026-02-20 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sku_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotevalidade',
            name='estoque_display',
            field=models.CharField(blank=True, help_text='Texto original da planilha ex: 388/06', max_length=50, null=True, verbose_name='Estoque Original (Display)'),
        ),
        migrations.AddField(
            model_name='sku',
            name='fator_conversao',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de unidades por caixa/fardo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Fator de Conversão'),
        ),
        migrations.AlterField(
            model_name='lotevalidade',
            name='data_validade',
            field=models.DateField(blank=True, db_index=True, help_text='Pode ser nulo para estoque base sem validade definida', null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unidade_medida',
            field=models.CharField(default='UN', help_text='Unidade flexível (UN, CX, FD, DZ, PCT, etc.)', max_length=20, verbose_name='Unidade de Medida'),
        ),
    ]
