# Generated by Django 4.2.27 on 2026-03-02 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_fator_conversao_estoque_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoalerta',
            name='dias_para_critico',
        ),
        migrations.RemoveField(
            model_name='configuracaoalerta',
            name='dias_para_pre_bloqueio',
        ),
        migrations.AddField(
            model_name='configuracaoalerta',
            name='dias_bloqueado',
            field=models.PositiveIntegerField(default=30, help_text='Quantidade de dias antes do vencimento para status BLOQUEADO (padrão: 30)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Bloqueado'),
        ),
        migrations.AddField(
            model_name='configuracaoalerta',
            name='dias_extremamente_critico',
            field=models.PositiveIntegerField(default=7, help_text='Quantidade de dias antes do vencimento para status EXTREMAMENTE CRÍTICO (padrão: 7)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Extremamente Crítico'),
        ),
        migrations.AddField(
            model_name='configuracaoalerta',
            name='dias_pre_bloqueio',
            field=models.PositiveIntegerField(default=60, help_text='Quantidade de dias antes do vencimento para status PRÉ-BLOQUEIO (padrão: 60)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Pré-Bloqueio'),
        ),
        migrations.AlterField(
            model_name='usuariounidade',
            name='papel',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('DIRETORIA', 'Diretoria')], default='VENDEDOR', max_length=50, verbose_name='Papel na Unidade'),
        ),
    ]
