# Generated by Django 4.2.27 on 2026-03-03 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_configuracaoalerta_dias_para_critico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_arquivo', models.CharField(choices=[('GRADE', 'Grade 020502'), ('CONTAGEM', 'Contagem')], max_length=20, verbose_name='Tipo de Arquivo')),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='SUCESSO', max_length=20, verbose_name='Status')),
                ('linhas_processadas', models.PositiveIntegerField(default=0, verbose_name='Linhas Processadas')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_uploads', to='core.unidadenegocio', verbose_name='Unidade de Negócio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Upload',
                'verbose_name_plural': 'Históricos de Upload',
                'ordering': ['-created_at'],
            },
        ),
    ]
