# Generated by Django 4.2.27 on 2026-03-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariounidade',
            name='papel',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('DIRETORIA', 'Diretoria'), ('ADMIN', 'Administrador')], default='VENDEDOR', max_length=50, verbose_name='Papel na Unidade'),
        ),
    ]
