# Generated by Django 4.2.27 on 2026-06-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuariounidade_papel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='lote',
        ),
        migrations.AddField(
            model_name='sku',
            name='qtd_buffer_020304',
            field=models.IntegerField(default=0, help_text='Estoque retido em pedidos de saída', verbose_name='Buffer em Pedidos (020304)'),
        ),
        migrations.AddField(
            model_name='sku',
            name='qtd_disponivel_venda',
            field=models.IntegerField(default=0, help_text='Calculado: total - buffer', verbose_name='Disponível para Venda'),
        ),
        migrations.AddField(
            model_name='sku',
            name='qtd_total_020502',
            field=models.IntegerField(default=0, help_text='Estoque físico real total convertido em unidades base', verbose_name='Estoque Total (020502)'),
        ),
        migrations.AddField(
            model_name='sku',
            name='validade_fim_range',
            field=models.DateField(blank=True, help_text='Data de validade mais longa do estoque disponível', null=True, verbose_name='Fim do Range de Validade'),
        ),
        migrations.AddField(
            model_name='sku',
            name='validade_inicio_range',
            field=models.DateField(blank=True, help_text='Data de validade do produto mais antigo disponível (FEFO reverso)', null=True, verbose_name='Início do Range de Validade'),
        ),
        migrations.DeleteModel(
            name='LoteValidade',
        ),
    ]
