# Generated by Django 4.2.27 on 2026-06-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_movimentacaoestoque_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoupload',
            name='tipo_arquivo',
            field=models.CharField(choices=[('GRADE', 'Grade 020502'), ('CONTAGEM', 'Contagem'), ('FEFO', 'Estoque FEFO (3 Arquivos)')], max_length=20, verbose_name='Tipo de Arquivo'),
        ),
    ]
