# Generated by Django 4.2.27 on 2026-06-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_historicoupload_tipo_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('chave', models.CharField(db_index=True, help_text='Ex: consultar_estoque, itens_criticidade, gestao_usuarios. Deve bater com o Flutter.', max_length=50, unique=True, verbose_name='Chave do Módulo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Menu')),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone ou identificador string para o Flutter (Ex: inventory, warning).', max_length=50, null=True, verbose_name='Nome do Ícone')),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem de Exibição')),
                ('globalmente_ativo', models.BooleanField(default=True, help_text='Se desativado aqui, nenhum usuário do sistema verá este menu, independente do papel.', verbose_name='Globalmente Ativo')),
            ],
            options={
                'verbose_name': 'Módulo de Menu',
                'verbose_name_plural': 'Módulos de Menu',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('papel', models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('DIRETORIA', 'Diretoria'), ('ADMIN', 'Administrador')], db_index=True, max_length=50, verbose_name='Papel com Acesso')),
                ('visivel', models.BooleanField(default=True, help_text='Determina se este papel específico pode ver este menu.', verbose_name='Visível')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='core.modulomenu', verbose_name='Módulo/Menu')),
            ],
            options={
                'verbose_name': 'Permissão de Menu',
                'verbose_name_plural': 'Permissões de Menu',
                'unique_together': {('modulo', 'papel')},
            },
        ),
    ]
