# Generated by Django 4.2.27 on 2026-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuariounidade_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaomenu',
            name='papel',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('DIRETORIA', 'Diretoria'), ('ADMIN', 'Administrador'), ('CONTROLE', 'Controle')], db_index=True, max_length=50, verbose_name='Papel com Acesso'),
        ),
    ]
