# Generated by Django 4.2.27 on 2026-07-06 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_permissaomenu_papel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoCriticoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantidade_critica', models.IntegerField(verbose_name='Quantidade Crítica')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_manuais', to='core.sku', verbose_name='Produto (SKU)')),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_criticos', to='core.unidadenegocio', verbose_name='Unidade de Negócio')),
                ('usuario_lancamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meus_lancamentos_criticos', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
            ],
            options={
                'verbose_name': 'Lançamento Crítico Manual',
                'verbose_name_plural': 'Lançamentos Críticos Manuais',
                'ordering': ['-created_at'],
            },
        ),
    ]
