# Generated by Django 4.2.27 on 2026-07-16 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lancamentocriticomanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocriticomanual',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução'),
        ),
        migrations.AddField(
            model_name='lancamentocriticomanual',
            name='motivo_resolucao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo da Baixa'),
        ),
        migrations.AddField(
            model_name='lancamentocriticomanual',
            name='usuario_resolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolucoes_criticas', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por'),
        ),
    ]
