# Generated by Django 4.2.27 on 2026-07-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lancamentocriticomanual_data_resolucao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamentocriticomanual',
            options={'ordering': ['data_validade'], 'verbose_name': 'Lançamento Crítico', 'verbose_name_plural': 'Lançamentos Críticos'},
        ),
        migrations.AddField(
            model_name='lancamentocriticomanual',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AddField(
            model_name='lancamentocriticomanual',
            name='origem',
            field=models.CharField(choices=[('APP', 'Aplicativo'), ('PLANILHA', 'Planilha Importada')], default='APP', max_length=15, verbose_name='Origem do Lançamento'),
        ),
        migrations.AlterField(
            model_name='lancamentocriticomanual',
            name='data_validade',
            field=models.DateField(verbose_name='Data de Validade (Crítica)'),
        ),
        migrations.AlterField(
            model_name='lancamentocriticomanual',
            name='quantidade_critica',
            field=models.IntegerField(verbose_name='Quantidade Crítica Retida'),
        ),
        migrations.AlterField(
            model_name='lancamentocriticomanual',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_criticos', to='core.sku'),
        ),
        migrations.AlterField(
            model_name='lancamentocriticomanual',
            name='unidade_negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_criticos', to='core.unidadenegocio'),
        ),
    ]
